version: '2'

services:
    caddy-core:
        container_name: caddy-core
        restart: always
        build: ./caddy-core
        ports:
            - "127.0.0.1:6890:80"
        volumes:
            - ./caddy-core/:/etc/caddy/

    caddy-hivemind:
        container_name: caddy-hivemind
        restart: always
        build: ./caddy-hivemind
        ports:
            - "127.0.0.1:6880:80"
        volumes:
            - ./caddy-hivemind/:/etc/caddy/

    rpc-core:
        image: hive
        restart: "no"
        container_name: rpc-core
        command: hived --data-dir=/steem/witness_node_data_dir
        volumes:
            - /hive/rpc1:/steem
            - /shmhive/rpc1:/shm
        ports:
            - "8090"
            - "8091"
            - "0.0.0.0:8090:8090"
            - "0.0.0.0:8091:8091"

    jussi:
        restart: "always"
        image: "steemit/jussi:latest"
        ports:
        - "127.0.0.1:8080:8080"
        - "127.0.0.1:7777:7777"
        environment:
            JUSSI_REDIS_URL: redis://redis1:6379
            JUSSI_REDIS_READ_REPLICA_URLS: redis://redis2:6379
#            JUSSI_STATSD_URL: statsd://statsd:8125
        env_file: jussi/.env
        volumes:
        - ./jussi/DEV_config.json:/app/DEV_config.json

    redis1:
        restart: "always"
        image: "redis:3.2"

    redis2:
        restart: "always"
        image: "redis:3.2"
        ports:
        - "6379"


#    statsd:
#        restart: "no"
#        image: "statsd"
#        ports:
#        - "8125:8125/udp"

networks:
    default:
        driver: 'bridge'
        #external:
        #    name: hivenet

