version: '2'

services:
    nginx-core:
        container_name: nginx-core
        restart: always
        build: ./nginx-core
        ports:
            - "127.0.0.1:8877:80"
            - "80"

    nginx-acchist:
        container_name: nginx-acchist
        restart: always
        build: ./nginx-acchist
        ports:
            - "127.0.0.1:8878:80"
            - "80"

    rpc-core:
        image: hive-fullmem-mira 
        container_name: rpc-core
        command: steemd --data-dir=/steem/witness_node_data_dir
        volumes:
            - /hive/rpc1:/steem
            - /shmhive/rpc1:/shm
        ports:
            - "8090"
            - "8091"

    rpc-acchist:
        image: hive-lowmem-nomira
        container_name: rpc-acchist
        command: steemd --data-dir=/steem/witness_node_data_dir
        volumes:
            - /hive/rpc2:/steem
            - /shmhive/rpc2:/shm
        ports:
            - "8090"
            - "8091"

    jussi:
        restart: "no"
        image: "steemit/jussi:latest"
        ports:
        - "127.0.0.1:8080:8080"
        - "127.0.0.1:7777:7777"
        environment:
            JUSSI_REDIS_URL: redis://redis1:6379
            JUSSI_REDIS_READ_REPLICA_URLS: redis://redis2:6379
#            JUSSI_STATSD_URL: statsd://statsd:8125
        env_file: jussi/.env
        volumes:
        - ./jussi/DEV_config.json:/app/DEV_config.json

    redis1:
        restart: "no"
        image: "redis:3.2"

    redis2:
        restart: "no"
        image: "redis:3.2"
        ports:
        - "6379"


#    statsd:
#        restart: "no"
#        image: "statsd"
#        ports:
#        - "8125:8125/udp"

networks:
    default:
        driver: 'bridge'
